// Generated by gencpp from file servicetest/hjh.msg
// DO NOT EDIT!


#ifndef SERVICETEST_MESSAGE_HJH_H
#define SERVICETEST_MESSAGE_HJH_H

#include <ros/service_traits.h>


#include <servicetest/hjhRequest.h>
#include <servicetest/hjhResponse.h>


namespace servicetest
{

struct hjh
{

typedef hjhRequest Request;
typedef hjhResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct hjh
} // namespace servicetest


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::servicetest::hjh > {
  static const char* value()
  {
    return "4ea70316ac12589c73d4bd02fe66905f";
  }

  static const char* value(const ::servicetest::hjh&) { return value(); }
};

template<>
struct DataType< ::servicetest::hjh > {
  static const char* value()
  {
    return "servicetest/hjh";
  }

  static const char* value(const ::servicetest::hjh&) { return value(); }
};


// service_traits::MD5Sum< ::servicetest::hjhRequest> should match 
// service_traits::MD5Sum< ::servicetest::hjh > 
template<>
struct MD5Sum< ::servicetest::hjhRequest>
{
  static const char* value()
  {
    return MD5Sum< ::servicetest::hjh >::value();
  }
  static const char* value(const ::servicetest::hjhRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicetest::hjhRequest> should match 
// service_traits::DataType< ::servicetest::hjh > 
template<>
struct DataType< ::servicetest::hjhRequest>
{
  static const char* value()
  {
    return DataType< ::servicetest::hjh >::value();
  }
  static const char* value(const ::servicetest::hjhRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::servicetest::hjhResponse> should match 
// service_traits::MD5Sum< ::servicetest::hjh > 
template<>
struct MD5Sum< ::servicetest::hjhResponse>
{
  static const char* value()
  {
    return MD5Sum< ::servicetest::hjh >::value();
  }
  static const char* value(const ::servicetest::hjhResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::servicetest::hjhResponse> should match 
// service_traits::DataType< ::servicetest::hjh > 
template<>
struct DataType< ::servicetest::hjhResponse>
{
  static const char* value()
  {
    return DataType< ::servicetest::hjh >::value();
  }
  static const char* value(const ::servicetest::hjhResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICETEST_MESSAGE_HJH_H
