// Generated by gencpp from file servicetest/hjhRequest.msg
// DO NOT EDIT!


#ifndef SERVICETEST_MESSAGE_HJHREQUEST_H
#define SERVICETEST_MESSAGE_HJHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace servicetest
{
template <class ContainerAllocator>
struct hjhRequest_
{
  typedef hjhRequest_<ContainerAllocator> Type;

  hjhRequest_()
    : age(0)
    , name()
    , school()  {
    }
  hjhRequest_(const ContainerAllocator& _alloc)
    : age(0)
    , name(_alloc)
    , school(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _age_type;
  _age_type age;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _school_type;
  _school_type school;





  typedef boost::shared_ptr< ::servicetest::hjhRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servicetest::hjhRequest_<ContainerAllocator> const> ConstPtr;

}; // struct hjhRequest_

typedef ::servicetest::hjhRequest_<std::allocator<void> > hjhRequest;

typedef boost::shared_ptr< ::servicetest::hjhRequest > hjhRequestPtr;
typedef boost::shared_ptr< ::servicetest::hjhRequest const> hjhRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servicetest::hjhRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servicetest::hjhRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace servicetest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::servicetest::hjhRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servicetest::hjhRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicetest::hjhRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servicetest::hjhRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicetest::hjhRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servicetest::hjhRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servicetest::hjhRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaf0160f0047e4b8eb2ba65ee622b437";
  }

  static const char* value(const ::servicetest::hjhRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaf0160f0047e4b8ULL;
  static const uint64_t static_value2 = 0xeb2ba65ee622b437ULL;
};

template<class ContainerAllocator>
struct DataType< ::servicetest::hjhRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servicetest/hjhRequest";
  }

  static const char* value(const ::servicetest::hjhRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servicetest::hjhRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int16 age\n\
string name\n\
string school\n\
";
  }

  static const char* value(const ::servicetest::hjhRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servicetest::hjhRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.age);
      stream.next(m.name);
      stream.next(m.school);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct hjhRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servicetest::hjhRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servicetest::hjhRequest_<ContainerAllocator>& v)
  {
    s << indent << "age: ";
    Printer<int16_t>::stream(s, indent + "  ", v.age);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "school: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.school);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICETEST_MESSAGE_HJHREQUEST_H
